apiVersion: v1
kind: ServiceAccount
metadata:
  name: opentelemetry-collector
  namespace: opentelemetry-system
  annotations:
    iam.gke.io/gcp-service-account: "opentelemetry-collector-dev@yan-lab.iam.gserviceaccount.com" 